version: 0.2
phases:
  build:
    commands:
      - aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws/a3c3g9z1
      - docker build -t pythonflask .
      - docker tag pythonflask:latest public.ecr.aws/a3c3g9z1/pythonflask:latest
      - docker push public.ecr.aws/a3c3g9z1/pythonflask:latest
