version: 0.2
phases:
  build:
    commands:
      - aws ecr get-login-password | docker login --username AWS --password-stdin public.ecr.aws/a3c3g9z1
      - docker build -t builtimage .
      - docker tag builtimage:latest public.ecr.aws/a3c3g9z1/dockerpython-flask:latest
      - docker push  public.ecr.aws/a3c3g9z1/dockerpython-flask:latest
